In [ ]:
# -*- coding: utf-8 -*-
import sys
import numpy as np
sys.path.insert(0, r'C:\Users\Asus\Desktop\Bioinformática\2º Ano\1º Semestre\Sistemas inteligentes\si\src\si')
sys.path.insert(0, r'C:\Users\Asus\Desktop\Bioinformática\2º Ano\1º Semestre\Sistemas inteligentes\si\src\si\io')
from sklearn.preprocessing import StandardScaler
from csv1 import read_csv
from metrics.cross_entropy import cross_entropy, cross_entropy_derivative
from model_selection.split import train_test_split
from neural_networks.layers import Dense, Sigmoid_Activation, SoftMaxActivation, ReLUActivation
from neural_networks.nn import NN

In [2]:
from data.dataset import Dataset

X = np.array([[0,0], [0,1], [1,0], [1,2]])

Y = np.array([1, 0, 0, 1])

dataset = Dataset(X, Y, ['x1', 'x2'], 'x1 XNOR x2')
print(dataset.print_dataframe())


w1 = np.array([[20, -20], [20, -20]])

b1 = np.array([[-30, 10]])


l1 = Dense(input_size = 2, output_size=2)
l1.weights = w1
l1.bias = b1


w2 = np.array([[20], [20]])

b2 = np.array([[-10]])

l2 = Dense(input_size = 2, output_size=1)
l2.weights = w2
l2.bias = b2

l1_sa = Sigmoid_Activation()
l2_sa = Sigmoid_Activation()

nn_model_sa = NN(layers=[l1, l1_sa, l2, l2_sa])
nn_model_sa.fit(dataset=dataset)


print(nn_model_sa.predict(dataset))

   x1  x2
1   0   0
0   0   1
0   1   0
1   1   2
[[9.99954561e-01]
 [4.54803785e-05]
 [4.54803785e-05]
 [9.99954602e-01]]


### Exercise 12.2: Build a NN model for the breast-bin.csv dataset.

In [2]:
breast_bin = r"C:\Users\Asus\Desktop\Bioinformática\2º Ano\1º Semestre\Sistemas inteligentes\si\datasets\breast-bin.csv"
bb_dataset = read_csv(breast_bin, sep=",", features = False, label=True)

In [3]:
bb_dataset.X = StandardScaler().fit_transform(bb_dataset.X)

In [4]:
bb_train, bb_test = train_test_split(bb_dataset)

In [5]:
bb_l1 = Dense(input_size = 9, output_size = 9) 
bb_l2 = Dense(input_size = 9, output_size = 4)
bb_l3 = Dense(input_size = 4, output_size = 1)

bb_l1_activation = ReLUActivation()
bb_l2_activation = ReLUActivation()
bb_l3_activation = Sigmoid_Activation()

bb_model = NN(
    layers=[bb_l1, bb_l1_activation, bb_l2, bb_l2_activation, bb_l3, bb_l3_activation], verbose = True)

In [6]:
bb_model.fit(dataset = bb_train)

Epoch 1/1000 - cost: 0.12500027307144176
Epoch 2/1000 - cost: 0.1249838939140976
Epoch 3/1000 - cost: 0.12496753477613932
Epoch 4/1000 - cost: 0.12495119592413331
Epoch 5/1000 - cost: 0.12493487696141407
Epoch 6/1000 - cost: 0.1249185779632179
Epoch 7/1000 - cost: 0.1249022989246839
Epoch 8/1000 - cost: 0.12488603983551981
Epoch 9/1000 - cost: 0.12486980023552852
Epoch 10/1000 - cost: 0.12485358035464883
Epoch 11/1000 - cost: 0.12483737938160945
Epoch 12/1000 - cost: 0.12482119633068318
Epoch 13/1000 - cost: 0.12480503331318014
Epoch 14/1000 - cost: 0.12478889049572649
Epoch 15/1000 - cost: 0.12477276789838362
Epoch 16/1000 - cost: 0.12475666526242321
Epoch 17/1000 - cost: 0.12474058267781003
Epoch 18/1000 - cost: 0.12472452023357691
Epoch 19/1000 - cost: 0.12470847795056957
Epoch 20/1000 - cost: 0.1246924557398398
Epoch 21/1000 - cost: 0.12467645370017222
Epoch 22/1000 - cost: 0.12466047175096723
Epoch 23/1000 - cost: 0.12464450976411542
Epoch 24/1000 - cost: 0.12462856770987697
Epoch

In [7]:
bb_model.predict(dataset = bb_test)

array([[0.42565801],
       [0.42565538],
       [0.4256558 ],
       [0.42565428],
       [0.42565601],
       [0.42565484],
       [0.42565928],
       [0.4256562 ],
       [0.4256547 ],
       [0.42565982],
       [0.42565614],
       [0.42565901],
       [0.42565113],
       [0.42565868],
       [0.42565605],
       [0.42565531],
       [0.42565601],
       [0.42565573],
       [0.42565795],
       [0.42565607],
       [0.42565418],
       [0.42565013],
       [0.42565567],
       [0.42565902],
       [0.42565724],
       [0.42565627],
       [0.42565509],
       [0.42565579],
       [0.42565474],
       [0.42565584],
       [0.42565708],
       [0.4256561 ],
       [0.42566523],
       [0.42565563],
       [0.42565619],
       [0.4256551 ],
       [0.42565585],
       [0.42565567],
       [0.42565874],
       [0.42566023],
       [0.42565571],
       [0.42565531],
       [0.42565654],
       [0.42565561],
       [0.42565414],
       [0.4256591 ],
       [0.42565546],
       [0.425

### Exercise 12.3: Build a NN model for the cpu.csv dataset.

In [18]:
cpu = r"C:\Users\Asus\Desktop\Bioinformática\2º Ano\1º Semestre\Sistemas inteligentes\si\datasets\cpu.csv"
cpu_dataset = read_csv(cpu, sep=",", features=True, label=True)

In [19]:
cpu_dataset.X = StandardScaler().fit_transform(cpu_dataset.X)

In [20]:
cpu_train, cpu_test = train_test_split(cpu_dataset)

In [21]:
cpu_l1 = Dense(input_size = 6, output_size = 6)
cpu_l2 = Dense(input_size = 6, output_size = 4)
cpu_l3 = Dense(input_size = 4, output_size = 1)

cpu_l1_activation = ReLUActivation()
cpu_l2_activation = ReLUActivation()
cpu_l3_activation = Sigmoid_Activation()

cpu_model = NN(
    layers=[cpu_l1, cpu_l1_activation, cpu_l2, cpu_l2_activation, cpu_l3, cpu_l3_activation], verbose = True)

In [22]:
cpu_model.fit(cpu_train)

Epoch 1/1000 - cost: 14424.672659505575
Epoch 2/1000 - cost: 14418.633752962372
Epoch 3/1000 - cost: 14412.86651913172
Epoch 4/1000 - cost: 14407.655552758655
Epoch 5/1000 - cost: 14403.15161277586
Epoch 6/1000 - cost: 14399.374194343654
Epoch 7/1000 - cost: 14396.25809662395
Epoch 8/1000 - cost: 14393.702899615413
Epoch 9/1000 - cost: 14391.60523650965
Epoch 10/1000 - cost: 14389.873761095356
Epoch 11/1000 - cost: 14388.433407707353
Epoch 12/1000 - cost: 14387.224649101141
Epoch 13/1000 - cost: 14386.20102898224
Epoch 14/1000 - cost: 14385.326472307323
Epoch 15/1000 - cost: 14384.572929228867
Epoch 16/1000 - cost: 14383.918483585627
Epoch 17/1000 - cost: 14383.345894459311
Epoch 18/1000 - cost: 14382.84149238914
Epoch 19/1000 - cost: 14382.394349965605
Epoch 20/1000 - cost: 14381.995659037328
Epoch 21/1000 - cost: 14381.638261634183
Epoch 22/1000 - cost: 14381.316294815824
Epoch 23/1000 - cost: 14381.024920022426
Epoch 24/1000 - cost: 14380.760115341549
Epoch 25/1000 - cost: 14380.518

Epoch 408/1000 - cost: 14375.705119673443
Epoch 409/1000 - cost: 14375.704450457697
Epoch 410/1000 - cost: 14375.703784769728
Epoch 411/1000 - cost: 14375.703122588366
Epoch 412/1000 - cost: 14375.702463886357
Epoch 413/1000 - cost: 14375.70180863912
Epoch 414/1000 - cost: 14375.701156822304
Epoch 415/1000 - cost: 14375.700508411783
Epoch 416/1000 - cost: 14375.699863383641
Epoch 417/1000 - cost: 14375.699221714198
Epoch 418/1000 - cost: 14375.698583379964
Epoch 419/1000 - cost: 14375.69794835765
Epoch 420/1000 - cost: 14375.697316624255
Epoch 421/1000 - cost: 14375.69668815693
Epoch 422/1000 - cost: 14375.696062933055
Epoch 423/1000 - cost: 14375.695440930187
Epoch 424/1000 - cost: 14375.694822126101
Epoch 425/1000 - cost: 14375.69420649878
Epoch 426/1000 - cost: 14375.693594026368
Epoch 427/1000 - cost: 14375.692984687254
Epoch 428/1000 - cost: 14375.69237845997
Epoch 429/1000 - cost: 14375.691775323277
Epoch 430/1000 - cost: 14375.691175256095
Epoch 431/1000 - cost: 14375.6905782375

Epoch 617/1000 - cost: 14375.616500246768
Epoch 618/1000 - cost: 14375.616239817813
Epoch 619/1000 - cost: 14375.615980403376
Epoch 620/1000 - cost: 14375.615721998198
Epoch 621/1000 - cost: 14375.61546459505
Epoch 622/1000 - cost: 14375.615208190782
Epoch 623/1000 - cost: 14375.614952779988
Epoch 624/1000 - cost: 14375.614698358186
Epoch 625/1000 - cost: 14375.614444920358
Epoch 626/1000 - cost: 14375.61419246151
Epoch 627/1000 - cost: 14375.613940976662
Epoch 628/1000 - cost: 14375.613690460954
Epoch 629/1000 - cost: 14375.613440909492
Epoch 630/1000 - cost: 14375.61319231743
Epoch 631/1000 - cost: 14375.612944679937
Epoch 632/1000 - cost: 14375.612697992237
Epoch 633/1000 - cost: 14375.612452249576
Epoch 634/1000 - cost: 14375.612207447188
Epoch 635/1000 - cost: 14375.611963580368
Epoch 636/1000 - cost: 14375.611720644441
Epoch 637/1000 - cost: 14375.61147863476
Epoch 638/1000 - cost: 14375.611237546706
Epoch 639/1000 - cost: 14375.610997375688
Epoch 640/1000 - cost: 14375.610758117

Epoch 814/1000 - cost: 14375.579824385033
Epoch 815/1000 - cost: 14375.57969373119
Epoch 816/1000 - cost: 14375.579563488232
Epoch 817/1000 - cost: 14375.57943365435
Epoch 818/1000 - cost: 14375.579304228018
Epoch 819/1000 - cost: 14375.57917520757
Epoch 820/1000 - cost: 14375.579046591329
Epoch 821/1000 - cost: 14375.57891837765
Epoch 822/1000 - cost: 14375.578790565043
Epoch 823/1000 - cost: 14375.578663151695
Epoch 824/1000 - cost: 14375.578536135965
Epoch 825/1000 - cost: 14375.578409516225
Epoch 826/1000 - cost: 14375.578283290864
Epoch 827/1000 - cost: 14375.578157458263
Epoch 828/1000 - cost: 14375.578032016832
Epoch 829/1000 - cost: 14375.577906964962
Epoch 830/1000 - cost: 14375.577782301078
Epoch 831/1000 - cost: 14375.5776580236
Epoch 832/1000 - cost: 14375.577534130953
Epoch 833/1000 - cost: 14375.577410621563
Epoch 834/1000 - cost: 14375.577287493852
Epoch 835/1000 - cost: 14375.577164746312
Epoch 836/1000 - cost: 14375.577042377094
Epoch 837/1000 - cost: 14375.5769203845


In [23]:
cpu_model.predict(dataset = cpu_test)

array([[0.99954956],
       [0.9995303 ],
       [0.99953029],
       [0.99961015],
       [0.99953031],
       [0.99956293],
       [0.9995303 ],
       [0.99953031],
       [0.99963646],
       [0.99956702],
       [0.99953655],
       [0.9995388 ],
       [0.99953026],
       [0.9995303 ],
       [0.99953159],
       [0.99953022],
       [0.99954468],
       [0.99953022],
       [0.99954887],
       [0.99953497],
       [0.99953046],
       [0.99953031],
       [0.9995441 ],
       [0.9995303 ],
       [0.99953028],
       [0.99953029],
       [0.99953031],
       [0.99953026],
       [0.9995303 ],
       [0.99953273],
       [0.99956392],
       [0.99953031],
       [0.99953031],
       [0.99953025],
       [0.99953029],
       [0.99953031],
       [0.99953035],
       [0.99957816],
       [0.99954578],
       [0.99953027],
       [0.99959838]])