### Avaliação Aula 9

#### Exercício 9: Redes neuronais, layers de ativação, regressão e multiclass

In [1]:
# -*- coding: utf-8 -*-

# modules
import sys
import numpy as np
sys.path.insert(0, r'C:\Users\Asus\Desktop\Bioinformática\2º Ano\1º Semestre\Sistemas inteligentes\si\src\si')

from data.dataset import Dataset
from neural_networks.nn import NN
from neural_networks.layers import Dense, Sigmoid_Activation, SoftMaxActivation, ReLUActivation, LinearActivation

#### 9.3) Constrói um modelo de redes neuronais considerando a seguinte topologia:
- O dataset de treino contém 32 features
- O problema é do tipo binário
- O modelo deve conter 3 Dense layers:
 - Dense layer de input
 - Dense layer com redução do número de neurónios (units) para metade
 - Dense layer final (output)
- Usa a SigmoidActivation como layer de ativação

In [2]:
# training dataset
np.random.seed(32)
X = np.random.randn(120, 32)
y = np.random.randint(0, 2, 120)

dataset_bin = Dataset(X, y)
dataset_bin.y

array([0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0,
       1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 0, 0])

In [3]:
l1 = Dense(input_size=32, output_size=32)
l2 = Dense(input_size=32, output_size=32//2)
l3 = Dense(input_size=32//2, output_size=1) #if score is <0.5 the output is 0, and if score is >0.5 the output is 1

l1_seq = Sigmoid_Activation()
l2_seq = Sigmoid_Activation()
l3_seq = Sigmoid_Activation()

layers = [l1, l1_seq, l2, l2_seq, l3, l3_seq] #list of layers
nn_model = NN(layers) 

In [4]:
nn_model.fit(dataset = dataset_bin)

In [ ]:
nn_model.predict(dataset = dataset_bin)

#### 9.4) Constrói um modelo de redes neuronais considerando a seguinte topologia:
- O dataset de treino contém 32 features
- O problema é do tipo multiclass com 3 classes
- O modelo deve conter 3 Dense layers:
 - Dense layer de input
 - Dense layer com redução do número de neurónios (units) para metade
 - Dense layer final (output)
- Usa a SigmoidActivation como layer de ativação
- Usa a SoftMaxActivation como última layer de ativação

In [6]:
# training dataset
np.random.seed(32)
X = np.random.randn(120, 32)
y = np.random.randint(0, 3, 120)

dataset2 = Dataset(X, y)
dataset2.y

array([2, 2, 2, 2, 0, 1, 2, 0, 2, 1, 2, 0, 2, 1, 2, 1, 0, 2, 2, 0, 1, 0,
       2, 0, 1, 1, 2, 1, 2, 2, 2, 1, 1, 2, 2, 2, 2, 0, 2, 1, 1, 1, 1, 0,
       1, 2, 2, 0, 0, 0, 1, 1, 2, 2, 1, 2, 1, 0, 2, 0, 2, 1, 2, 1, 2, 0,
       2, 2, 1, 0, 0, 1, 0, 2, 2, 1, 1, 0, 1, 0, 0, 0, 0, 2, 1, 0, 0, 1,
       2, 2, 2, 2, 0, 0, 0, 0, 2, 0, 0, 0, 1, 1, 0, 1, 2, 2, 0, 0, 1, 0,
       0, 1, 2, 2, 1, 2, 1, 2, 1, 2])

In [7]:
l1 = Dense(input_size = 32, output_size = 32)
l2 = Dense(input_size = 32, output_size = 32//2)
l3 = Dense(input_size = 32//2, output_size = 3)

l1_class_sa = Sigmoid_Activation()
l2_class_sa = Sigmoid_Activation()
l3_class_sma = SoftMaxActivation()

layers=[ l1, l1_class_sa, l2, l2_class_sa, l3, l3_class_sma]
model_class = NN(layers)

In [ ]:
model_class.fit(dataset2)

In [ ]:
model_class.predict(dataset2)

#### 9.5) Constrói um modelo de redes neuronais considerando a seguinte topologia:
- O dataset de treino contém 32 features
- O problema é do tipo regressão
- O modelo deve conter 3 Dense layers:
 - Dense layer de input
 - Dense layer com redução do número de neurónios (units) para metade
 - Dense layer final (output)
- Usa a ReLU como layer de ativação
- Considera que o modelo deve acabar com uma ativação linear

In [15]:
np.random.seed(32)
X = np.random.randn(120, 32)
y = np.random.randn(120)

dataset3 = Dataset(X, y)
dataset3.y

array([ 0.71547353, -0.71872666, -1.98814586, -0.75200279,  0.88117931,
       -0.44468611,  1.05978473,  0.57672146,  0.13964803,  1.57258772,
       -1.19685552, -1.25685322, -0.51459268, -0.51529445, -1.06552076,
        0.44061408,  0.68298176,  3.11335987, -0.54432467, -2.0969254 ,
       -0.04352082, -1.38943868, -0.73688503, -1.31724886, -0.20592268,
        0.98020279, -2.27105266,  0.36387381,  0.30752718,  0.09439799,
       -1.54788962, -0.4545496 ,  1.55982121,  1.2264142 ,  0.12042863,
       -0.7883922 ,  1.07002129,  0.35085381, -1.08350751,  0.13129866,
       -1.20183412, -0.21018285, -1.5959463 ,  0.70304565, -2.02793566,
       -1.06975587,  0.7848609 ,  0.01700652,  1.20791878,  0.66691887,
       -1.28821386,  0.56877822,  1.36115828, -0.20157567, -0.00519527,
       -1.58902907, -0.45444925, -2.00597599, -1.16037829, -1.29167892,
       -0.50855262, -0.02113207,  0.73274978,  0.01196069,  2.2383034 ,
        1.49573213, -0.32104883, -0.75577796, -1.15301118,  0.14

In [16]:
l1_reg = Dense(input_size=32, output_size=32)
l2_reg = Dense(input_size=32, output_size=32//2)
l3_reg = Dense(input_size=32//2, output_size=1)

l1_relu = ReLUActivation()
l2_relu = ReLUActivation()
l3_lin = LinearActivation()


layers = [l1_reg, l1_relu, l2_reg, l2_relu, l3_reg, l3_lin]
nn_model_reg = NN(layers) 

In [ ]:
nn_model_reg.fit(dataset3)

In [ ]:
nn_model_reg.predict(dataset3)